# Generated by Django 5.2.13 on 2026-04-18 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin/SuperAdmin who created this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('banned', 'Banned'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status_reason',
            field=models.CharField(blank=True, default='', help_text='Reason for suspension/ban', max_length=300),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, help_text='Action type: user.created, role.changed, user.suspended, etc.', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Action-specific data: old_role, new_role, reason, ip_address, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(help_text='The admin who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(help_text='The user the action was performed on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_auditlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='accounts_au_actor_i_48e6fd_idx'), models.Index(fields=['target_user', '-created_at'], name='accounts_au_target__5aa529_idx'), models.Index(fields=['action', '-created_at'], name='accounts_au_action_f18cdc_idx')],
            },
        ),
    ]
