# Generated by Django 5.2.13 on 2026-04-09 10:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('layout_definition', models.JSONField(default=dict, help_text='JSON structure defining page layout blocks')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('newspaper_name', models.CharField(default='Media Puls', max_length=200)),
                ('edition_number', models.PositiveIntegerField(db_index=True)),
                ('publication_date', models.DateField(db_index=True)),
                ('page_size', models.CharField(choices=[('TABLOID', 'Tabloid (11×17")'), ('BROADSHEET', 'Broadsheet (15×22")'), ('A4', 'A4 (210×297mm)'), ('LETTER', 'Letter (8.5×11")')], default='TABLOID', max_length=20)),
                ('layout_mode', models.CharField(choices=[('FIXED_TEMPLATE', 'Fixed Template')], default='FIXED_TEMPLATE', max_length=20)),
                ('style_preset', models.CharField(choices=[('DEFAULT', 'Default'), ('CLASSIC', 'Classic'), ('MODERN', 'Modern')], default='DEFAULT', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=20)),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='editions/pdfs/')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('newspaper_name', 'edition_number')},
            },
        ),
        migrations.CreateModel(
            name='PDFGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=20)),
                ('progress_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='editions.edition')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(max_length=500)),
                ('subheadline', models.CharField(blank=True, default='', max_length=500)),
                ('byline', models.CharField(blank=True, default='', max_length=200)),
                ('content_raw', models.TextField()),
                ('content_format', models.CharField(choices=[('PLAINTEXT', 'Plain Text'), ('MARKDOWN', 'Markdown'), ('JSON', 'JSON'), ('YAML', 'YAML')], default='PLAINTEXT', max_length=20)),
                ('content_parsed', models.TextField(blank=True, default='', help_text='HTML output from parser')),
                ('priority', models.CharField(choices=[('HERO', 'Hero (Full Width)'), ('MAJOR', 'Major (3 Columns)'), ('STANDARD', 'Standard (2 Columns)'), ('MINOR', 'Minor (1 Column)')], db_index=True, default='STANDARD', max_length=20)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('highlights_mode', models.CharField(choices=[('NONE', 'None'), ('MANUAL', 'Manual'), ('EXTRACTIVE', 'Extractive'), ('LLM', 'LLM Generated')], default='NONE', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/images/')),
                ('image_caption', models.CharField(blank=True, default='', max_length=300)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Manual ordering within edition')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='editions.category')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='editions.edition')),
            ],
            options={
                'ordering': ['order', '-priority', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['edition', 'priority'], name='editions_ar_edition_28e061_idx'), models.Index(fields=['edition', 'order'], name='editions_ar_edition_e53cf9_idx')],
            },
        ),
    ]
