# Generated by Django 5.2.13 on 2026-04-10 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='edit_remark',
            field=models.CharField(blank=True, default='', help_text='Auto-set when Editor/Admin edits another user article', max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='edition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='edition',
            name='newspaper_name',
            field=models.CharField(default='Media Pulse', max_length=200),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author', 'created_at'], name='editions_ar_author__f370d1_idx'),
        ),
        migrations.AddIndex(
            model_name='edition',
            index=models.Index(fields=['created_by', 'status'], name='editions_ed_created_7de5b7_idx'),
        ),
    ]
