# Generated by Django 5.2.13 on 2026-04-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0002_article_author_article_edit_remark_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['page_number', 'display_order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='page_number',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='PDF page number for this category (0 = auto-place)'),
        ),
    ]
