# Generated by Django 5.2.13 on 2026-04-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0003_add_category_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='chief_editor',
            field=models.CharField(default='बलराम दीक्षित', help_text='प्रधान सम्पादक name for masthead', max_length=200),
        ),
        migrations.AddField(
            model_name='edition',
            name='inspiration_source',
            field=models.CharField(default='स्व0 सूर्यनारायण त्रिपाठी', help_text='प्रेरणा स्रोत name for masthead', max_length=200),
        ),
    ]
