# Generated by Django 5.2.13 on 2026-04-26 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0004_add_masthead_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Review'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='PUBLISHED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['edition', 'status'], name='editions_ar_edition_d5f4b6_idx'),
        ),
    ]
